include:
  - project: 'swarm/swarmops/devops/ci/ci-templates'
    ref: v1.1.0
    file: '/nexus/package.yml'

stages:
  - build package
  - deploy package
  - check approve

variables:
  PACKAGE_TYPE: deb

build:
  stage: build package
  before_script:
    - export STRIPPED_VERSION="${VERSION#v}"
    - echo $STRIPPED_VERSION
  script:
    - apt install -y asciidoc autoconf automake autogen
    - ./autogen.sh
    - ./configure '--with-pkgdst=/opt/swarm/' '--with-build-deb'
    - make build-deb
    - mv ./packages/deb/*.${PACKAGE_TYPE} .
