name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  create-release:
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup necessary package
        run: |
            sudo apt-get update
            sudo apt-get install -y libmnl-dev
            sudo apt-get install ruby-dev build-essential
            sudo gem i fpm -f
      - name: Build deb & rpm packages
        run: |
            ./autogen.sh
            ./configure '--with-pkgdst=/opt/swarm/' '--with-build-deb' '--with-build-rpm'
            make build-deb
            make build-rpm
        env:
          PKG_VERSION: ${{  github.ref_name  }}

      - name: Prepare sha256 checksum's
        run: |
          export STRIPPED_VERSION="${PKG_VERSION#v}"
          mv packages/deb/*.deb ${PACKAGE}-${STRIPPED_VERSION}-any.deb
          mv packages/rpm/*.rpm ${PACKAGE}-${STRIPPED_VERSION}-any.rpm
          for FILE in $(ls | grep -E '(deb|rpm)')
          do
            sha256sum "${FILE}" > "${FILE}_sha256sum"
          done
        env:
          PACKAGE: swarm-libnftnl
          PKG_VERSION: ${{  github.ref_name  }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: True
          artifacts: "*.deb, *sha256sum, *.rpm"
